apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgCLnxrJ21/rGCRvTFGEIIs8pzSLdUGUJMQLpwc705PITt/NKnNUHgBjj328xfA/TjzYbQ6s4rsc1aYyoSx8SSmho4ihdqPt33EZhrBLHsKAhuvy8rfeCxO3rtgCdwAS7uTrlAhJS15xj3SzErQ/nFsOlUG3kyJyJJdqaPiLJRI9+XnminMUbKmHoQ1H89EDesOyOg1mUaz76hbAeTfnThlI9v+TGE1oiImMgYJvmJNZyJxeg0zGHpHPttMBQbwq8bpdZ3mUpZ2vxPQKcgWQGU1T+HHw1WffKHV7C5Q7Ua/4TkUPExcAcLas12OyPT5bDD5rAUR+SCZ8gjgFxcCte24YG9MdqQx8xPdE4f3eUsXRI3o2xjFP45szizgcIPVXnWB/wuRzXe0HZQD6Ln7Xhibmsd1wLPHUokK2gWHyk+22Cf69sfS6F3SXczZJ37vfVvN/2WDfYdNxrWhmqcLHvGlGelKBoE9iU8NuSrLBHHk2/02Q9key1SJ/5/Lg/65DlBXd/8+VsW1KwKPOpTupirwjuzbPZTkO7vioDd+mCktdUF3I5cM6nIU9w6n/9MhIXOrClsVZ4G6LBbC836zpNtQc7S6aTJuB/Ie8LFJQzTtgVtPKtXTcb9NnHarxQPnxY0sR4YTg3qbhcn0y+0sLbDvKqcYM1Ohp4kA3Q37kGiFxKCHktWI3EiFhlDF15bc0hVwIfDFZy/AeWyZlgadYcbmaJnL9rPjOXOY/Nl9zLcU4E/E=
    password: AgAD17we8RuLXPdTO7cN4LYwdB8lXVg0jqH+Y5mEu1yNqAdAuwS9Wa65TwTNQsaiKgqeStRZFRhQYjDqnbPOduo3wWiv5mY+VmbjiqdLh2aogUKEqzhCyW0dcH5io+khoQGYs2x0kYsiYK3cFpwex/4rBScVb/tsOgPev8aJlMcO3pDAj6iXjH0Y8dXZ38k9tvtJ9CecG3RntbymsHeLgxqH1c1SsragGcsyzx+hA/q4Qgq3unUQUB+4BDtsH5BoE4VXyaaVx1hF3tnTOdpUPuA8U8jZPZjr1xmYwncwDwRP019Z2oHTmuZ4PBq1UrWvqnfCN08m3bO8tYTg+ctPyjRI7ymXZuW2nONzp3DyWVTLmfGTQak3H3x4f7ICoYBMWz5a8x11kVJxoLmtJjOVtCfgZBKVgcM2/Qh/cXTOgcjIyO0AXOYUbIzqmOvADUmmQn0hGmGSgGpowf3GqLvMNxdiCVy+/SdLYhg2dnj/zlD93m5G7ATDqyPZsskMnHQU9IrySG2FbiIIXpWyQaUUYkJAoXGhKo18MRd0XAbCKiEyX66K5RfzZgkavmyhzmBEJhW35oc1U4Vh8AHEjOTvPJ+7kLPjsQ7tQpcdxhT+PVpGdjBa7a0SXQ/cC2YqgigYJRrunIaEZDiTN93U/mPYc8izbBE10cWhr2XnJ9+n6WxbakG1j2LO3xwkD+meFCv69p89NoeUprZb32DVz99/m74=
    username: AgBwnJd0I4b++QWm0aao6HFxQcIHnuy/thvDy14maIOykzVWXJFKeDkLibH079ia3DQAi/NeekJZnG1+78C9ty3KGtEup0oqHbUWmQQ29V/CEP+/J5u8MoUp2ZnYwEW7nqb+on2gusIlbvZQTG/8ZNWllIB1n8cvQIoTGXMuPDXQIqFzoUaR62adz0iVrmDP24+UqrO5uEKtMIxwvyvoYgwirOBDTXzMuD7jdFsw5uVYi/Q7NWdjPXk93MUP4AIZsFrOfjFh/DNKpuYJvc5ygvcHCobsbxnG+Bz6u9NBQnTiUzbDJpTw21QQUt5pqK/pTlcGzz6vG6+CQvlzS9ulzOdR9kyCws+goZZvYFqgShbvd2bpb3Lu5s2buZ3qgoUkMdPAYCNPm4iEQKibU01LIbj1JCY5rjxsk7M9V0/nZ6Oew+RsyNuwLfZEdm4r2hpmaHZHHbyOl0CAeHLk1P7IGE6QZVJH1valbG6B7ZNQg9lFAwzRT2m+eXGBdgkNu6IAI/qSJWV02eV35rGxRPnLW0920DXJuzuo+LbN1wrZ9MM8qHLdBE3KWHjBdHK/7rA2ccW3wxh2LXAz1u365LJGoG2uckudOCcx6xJ73imqxEGlnmJACHdTn66zw7PdNr+1AUcOFhBVKyr4bKx0nJhQDz6hQWQWr6vRFAmfj2CP3YQhNsgtEXfZZRMb/jJw704jOOTeHx2HAyBnpzAtng==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque




